name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Download Go modules
        run: go mod download

      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1

      - name: Test
        run: faketty go test -cover -coverprofile=cover.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
